import { Dimensions, Platform, StyleSheet } from 'react-native';
import COLORS from '../colors/colors';

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

const styles = StyleSheet.create({
    containerPrimary: {
        width: width,
        height: 100,
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: Platform.OS === 'ios' ? 50 : 0,
    },
    container: {
        width: width,
        height: height * 1.05,
        backgroundColor: COLORS.primaryBlackHex,
    },
    TextHome: {
        fontSize: 30,
        color: COLORS.primaryWhiteHex,
        textAlign: 'left',
        marginTop: 10,
        marginLeft: 20,
        justifyContent: 'center',
        fontFamily: 'Poppins-Regular',
        letterSpacing: 3,
    },
    containerTextHome: {
        width: 200,
        height: 150,
    },
    InputContainerComponent: {
        flexDirection: 'row',
        margin: 20,
        borderRadius: 20,
        backgroundColor: COLORS.primaryDarkGreyHex,
        alignItems: 'center',
        justifyContent: 'center',
        width: width * 0.9,
        height: height * 0.08,
    },
    TextInputContainer: {
        width: '90%',
        height: height * 0.08,
        fontFamily: 'Poppins-500Medium',
        fontSize: 16,
        color: COLORS.primaryWhiteHex,
        alignItems: 'center',
    },
    item: {
        marginVertical: 8,
        borderRadius: 15,
        width: 110,
        justifyContent: 'center',
        alignItems: 'center',
        height: 40,
        marginRight: 10,
    },
    title: {
        fontSize: 17,
        color: COLORS.primaryWhiteHex,
        fontFamily: 'Poppins-Light',
        fontWeight: '600',
        padding: 6,
        borderRadius: 20,
    },
    titleDescription: {
        fontSize: 20,
        color: COLORS.primaryWhiteHex,
        fontFamily: 'Poppins-Light',
        fontWeight: '600',
        borderRadius: 20,
    },
    titleSecondCategory: {
        fontSize: 19,
        color: COLORS.primaryWhiteHex,
        fontFamily: 'Poppins-Regular',
        fontWeight: '800',
        marginBottom: 20,
        marginLeft: 20,
    },
    titleProduct: {
        fontSize: 13,
        color: COLORS.primaryWhiteHex,
        fontFamily: 'Poppins-Light',
        fontWeight: '500',
        marginRight: 50,
        marginLeft: 3,
    },
    titlePrice: {
        fontFamily: 'Poppins-Regular',
        fontSize: 14,
        color: COLORS.primaryWhiteHex,
        marginLeft: 4,
    },
    containerFlatList: {
        width: width,
        height: height * 0.08,
        marginLeft: 10,
        marginBottom: 10,
    },
    containerFlatListProduct: {
        width: width * 0.9,
        height: 230,
        marginLeft: 20,
    },
    FlatlistProduct: {
        width: width * 0.4,
        backgroundColor: COLORS.primaryDarkGreyHex,
        flex: 0.9,
        borderRadius: 16,
        gap: 10,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    FlatlistProductSecondCategory: {
        width: width * 0.45,
        backgroundColor: COLORS.primaryDarkGreyHex,
        height: height * 0.35,
        borderRadius: 16,
        gap: 10,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },

    FlatlistProductAlign: {
        width: width * 0.5,
        height: height * 0.2,
        marginLeft: 10,
        gap: 7,
    },
    star: {
        width: 80,
        height: 14,
        marginRight: 50,
    },
    starDescription: {
        width: 110,
        height: 24,
        color: COLORS.primaryOrangeHex,
    },

    titledesc: {
        fontSize: 14,
        color: COLORS.secondaryLightGreyHex,
        fontFamily: 'Poppins-Light',
        fontWeight: '600',
        borderRadius: 20,
    },
    containerSecondCategory: {
        width: width,
        height: height * 0.5,
        marginTop: 20,
    },
    Button: {
        width: width * 0.8,
        height: height * 0.08,
        backgroundColor: COLORS.primaryOrangeHex,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 40,
        borderRadius: 20,
        marginTop: 20,
    },
    containerSecondCategorytwo: {
        width: width * 0.9,
        height: height * 0.8,
    },
    containerScreenProduct: {
        width: width,
        height: height,
        backgroundColor: COLORS.primaryBlackHex,
    },
    containerImage: {
        width: width,
        height: height * 0.5,
    },
    cartItem: {
        width: width * 0.9,
        height: height * 0.2,
        backgroundColor: COLORS.primaryDarkGreyHex,
        borderRadius: 20,
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: 10,

        gap: 6,
    },
    containerCartItems: {
        width: '100%',
        height: '100%',
        backgroundColor: COLORS.primaryBlackHex,
        justifyContent: 'center',
        alignItems: 'center',
    },
    ContainerInfoProduct: {
        width: width,
        height: height * 0.2,
        marginTop: height * 0.3,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.secondaryBlackRGBA,
        borderTopRightRadius: 40,
        borderTopLeftRadius: 40,
        opacity: 0.8,
    },
    containerInfoProfiles: {
        flexDirection: 'row',
        margin: 10,
        borderRadius: 20,
        backgroundColor: COLORS.primaryDarkGreyHex,
        alignItems: 'center',
        justifyContent: 'center',
        width: width * 0.9,
        height: height * 0.08,
        gap: 5,
    },
    containerButtonIConback: {
        position: 'absolute',
        borderRadius: 20,
        width: 60,
        height: 60,
        backgroundColor: COLORS.secondaryBlackRGBA,
        marginLeft: 10,
        marginTop: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },

    cardContainer: {
        width: '90%',
        borderRadius: 20,
        height: 230,
        backgroundColor: '#9c44dc',
        marginTop: 20,
    },

    cardItemContainer: {
        flexDirection: 'row-reverse',
        width: '90%',
        height: 60,
    },
    containerDetailsProduct: {
        width: width,
        backgroundColor: COLORS.secondaryBlackRGBA,
        height: height * 0.16,
        position: 'absolute',
        marginTop: height * 0.34,
        justifyContent: 'center',
        alignItems: 'flex-start',
        borderTopEndRadius: 20,
        borderTopLeftRadius: 20,
        alignItems: 'flex-start',
    },
});

export default styles;
